logging:
  config: classpath:logback.xml
#  level:
#    com.example.springboot01.api: INFO
server:
  port: 1122

# 配置微服务地址
url:
  orderUrl: http://localhost:8081
  userUrl: http://localhost:8082

#关闭thymeleaf缓存
spring:
  thymeleaf:
    cache: false